### ISSUE TITLE
Move to RITlug GitLab Roadmap

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/TigerOS#153]
# What This Is
This issue is where we are going to create our roadmap for what is needed to be done in order to successfully migrate TigerOS over to git.ritlug.com

**Comment by Tjzabel** [comment]
# GitHub => GitLab Migration List
- [x] Upgrade hosted GitLab
- [x] Create TigerOS group 
- [x] Set mirroring up on GitLab, to pull from GitHub
- [x] Once initial mirror takes place, remove mirroring
- [x] Migrate all GitHub issues over to GitLab
- [x] Add current GitHub contributors as contributors to GitLab project, as applicable
- [x] Set correct permissions for current contributors
- [x] Set mirroring from GitLab => GitHub
- [x] Make note in GH that TigerOS development has now moved to git.ritlug.com/TigerOS
- [x] Go through issues and see what is relevant at this time for Fedora 30
- [x] Make issue board
- [x] ???
- [x] Profit!

**Comment by Tjzabel** [comment]
As I've gone through some of these checkpoints:

* Doing repository mirroring from GitHub => GitLab apparently isn't a feature in hosted gitlab-ce, so I simply pushed the branches over myself. Simple enough. 
* We will also need to move over all of our packages
* *We can download all our issues as a CSV and upload them to GitLab*

**Comment by Tjzabel** [comment]
Going to close this as complete.
